# Generated by Django 5.1.1 on 2024-09-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepositApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('periods', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('rate', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('periods__gte', 1), ('periods__lte', 60)), name='periods_range'), models.CheckConstraint(condition=models.Q(('amount__gte', 10000), ('amount__lte', 3000000)), name='amount_range'), models.CheckConstraint(condition=models.Q(('rate__gte', 1.0), ('rate__lte', 8.0)), name='rate_range')],
            },
        ),
    ]
